import type { StorybookConfig } from '@storybook/react-vite';

// Deliberately minimal: Storybook 10 core already ships controls, actions,
// backgrounds, viewport and `storybook/test` (play functions), so no addons are
// installed. `storybook init` was not used — its "recommended" setup pulls in
// addon-vitest + @vitest/browser and browser downloads the dashboard does not
// need. The builder reuses ../vite.config.ts, so `__LITEGEN_API_BASE__` and the
// React plugin behave exactly as in the app build.
const config: StorybookConfig = {
  // Co-located stories only, so no example scaffolding can creep back in.
  stories: ['../src/**/*.stories.@(ts|tsx)'],
  addons: [],
  framework: { name: '@storybook/react-vite', options: {} },
  // Real GLB/PNG bytes generated by fixtures/make_fixtures.py, served at
  // /fixtures/ so the 3D stories render actual meshes rather than placeholders.
  staticDirs: [{ from: './fixtures', to: '/fixtures' }],
  core: { disableTelemetry: true, disableWhatsNewNotifications: true },
};

export default config;
