// GENERATED by scripts/sync-models.mjs — do not edit by hand.
// Run `npm run sync-models` to refresh from the repo's models/*.yaml.
export interface ModelParam {
  name: string;
  kind: string;
  enum?: string[];
  default?: string | number | boolean;
  min?: number;
  max?: number;
}

export interface ModelRefRole {
  name: string;
  required: boolean;
  min: number;
  max: number;
}

export interface ModelEntry {
  id: string;
  provider: string;
  displayName: string;
  description: string;
  mediaType: 'image' | 'video';
  output: 'image' | 'video';
  capabilities: {
    textToImage: boolean;
    imageToImage: boolean;
    inpainting: boolean;
    textToVideo: boolean;
    imageToVideo: boolean;
  };
  sizes: string[];
  aspectRatios: string[];
  maxRefImages: number;
  refRoles: ModelRefRole[];
  promptLimits: { required: boolean; minLength?: number; maxLength?: number };
  params: ModelParam[];
  pricing?: { baseCostUsd: number };
  tags: string[];
  /** Most-applicable provider documentation URL. */
  referenceUrl?: string;
}

export const MODELS: ModelEntry[] = [
  {
    "id": "bedrock/amazon.nova-canvas-v1:0",
    "provider": "bedrock",
    "displayName": "Amazon Nova Canvas",
    "description": "Amazon Nova Canvas text-to-image (+ conditioning) via Bedrock InvokeModel (sync).",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": true,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [],
    "maxRefImages": 1,
    "refRoles": [
      {
        "name": "init",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 1024
    },
    "params": [
      {
        "name": "negative_prompt",
        "kind": "string"
      },
      {
        "name": "seed",
        "kind": "seed",
        "min": 0,
        "max": 2147483646
      },
      {
        "name": "guidance_scale",
        "kind": "float",
        "min": 1.1,
        "max": 10
      },
      {
        "name": "quality",
        "kind": "string",
        "enum": [
          "standard",
          "premium"
        ],
        "default": "standard"
      }
    ],
    "pricing": {
      "baseCostUsd": 0.04
    },
    "tags": [
      "text-to-image",
      "image-to-image"
    ],
    "referenceUrl": "https://docs.aws.amazon.com/nova/latest/userguide/getting-started-api.html"
  },
  {
    "id": "bedrock/amazon.nova-reel-v1:1",
    "provider": "bedrock",
    "displayName": "Amazon Nova Reel",
    "description": "Amazon Nova Reel text-to-video / image-to-video (async; output to S3).",
    "mediaType": "video",
    "output": "video",
    "capabilities": {
      "textToImage": false,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": true,
      "imageToVideo": true
    },
    "sizes": [],
    "aspectRatios": [],
    "maxRefImages": 1,
    "refRoles": [
      {
        "name": "first_frame",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 4000
    },
    "params": [
      {
        "name": "seed",
        "kind": "seed",
        "min": 0,
        "max": 2147483646
      },
      {
        "name": "duration_seconds",
        "kind": "float",
        "default": 6,
        "min": 6,
        "max": 120
      },
      {
        "name": "fps",
        "kind": "int",
        "default": 24,
        "min": 24,
        "max": 24
      },
      {
        "name": "resolution",
        "kind": "string",
        "enum": [
          "1280x720"
        ]
      }
    ],
    "pricing": {
      "baseCostUsd": 0.48
    },
    "tags": [
      "text-to-video",
      "image-to-video"
    ],
    "referenceUrl": "https://docs.aws.amazon.com/nova/latest/userguide/getting-started-api.html"
  },
  {
    "id": "bfl/flux-dev",
    "provider": "bfl",
    "displayName": "FLUX.1 [dev]",
    "description": "Black Forest Labs FLUX.1 dev (hosted) text-to-image.",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [],
    "maxRefImages": 0,
    "refRoles": [],
    "promptLimits": {
      "required": true,
      "maxLength": 10000
    },
    "params": [
      {
        "name": "seed",
        "kind": "seed",
        "min": 0,
        "max": 4294967294
      }
    ],
    "pricing": {
      "baseCostUsd": 0.025
    },
    "tags": [
      "text-to-image"
    ],
    "referenceUrl": "https://docs.bfl.ml/"
  },
  {
    "id": "bfl/flux-kontext-max",
    "provider": "bfl",
    "displayName": "FLUX.1 Kontext [max]",
    "description": "FLUX.1 Kontext max image editing.",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": true,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [
      "21:9",
      "16:9",
      "4:3",
      "1:1",
      "3:4",
      "9:16",
      "9:21"
    ],
    "maxRefImages": 1,
    "refRoles": [
      {
        "name": "init",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 10000
    },
    "params": [
      {
        "name": "seed",
        "kind": "seed",
        "min": 0,
        "max": 4294967294
      }
    ],
    "pricing": {
      "baseCostUsd": 0.08
    },
    "tags": [
      "text-to-image",
      "image-to-image",
      "editing"
    ],
    "referenceUrl": "https://docs.bfl.ml/"
  },
  {
    "id": "bfl/flux-kontext-pro",
    "provider": "bfl",
    "displayName": "FLUX.1 Kontext [pro]",
    "description": "FLUX.1 Kontext image editing (input_image base64 or URL).",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": true,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [
      "21:9",
      "16:9",
      "4:3",
      "1:1",
      "3:4",
      "9:16",
      "9:21"
    ],
    "maxRefImages": 1,
    "refRoles": [
      {
        "name": "init",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 10000
    },
    "params": [
      {
        "name": "seed",
        "kind": "seed",
        "min": 0,
        "max": 4294967294
      }
    ],
    "pricing": {
      "baseCostUsd": 0.04
    },
    "tags": [
      "text-to-image",
      "image-to-image",
      "editing"
    ],
    "referenceUrl": "https://docs.bfl.ml/"
  },
  {
    "id": "bfl/flux-pro",
    "provider": "bfl",
    "displayName": "FLUX [pro]",
    "description": "Black Forest Labs FLUX pro text-to-image.",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [],
    "maxRefImages": 0,
    "refRoles": [],
    "promptLimits": {
      "required": true,
      "maxLength": 10000
    },
    "params": [
      {
        "name": "seed",
        "kind": "seed",
        "min": 0,
        "max": 4294967294
      }
    ],
    "pricing": {
      "baseCostUsd": 0.05
    },
    "tags": [
      "text-to-image"
    ],
    "referenceUrl": "https://docs.bfl.ml/"
  },
  {
    "id": "bfl/flux-pro-1.1",
    "provider": "bfl",
    "displayName": "FLUX 1.1 [pro]",
    "description": "Black Forest Labs FLUX 1.1 pro text-to-image (Redux image_prompt ref).",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": true,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [],
    "maxRefImages": 1,
    "refRoles": [
      {
        "name": "redux",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 10000
    },
    "params": [
      {
        "name": "seed",
        "kind": "seed",
        "min": 0,
        "max": 4294967294
      }
    ],
    "pricing": {
      "baseCostUsd": 0.04
    },
    "tags": [
      "text-to-image"
    ],
    "referenceUrl": "https://docs.bfl.ml/"
  },
  {
    "id": "bfl/flux-pro-1.1-ultra",
    "provider": "bfl",
    "displayName": "FLUX 1.1 [pro] Ultra",
    "description": "FLUX 1.1 pro Ultra — high-resolution, aspect-ratio based.",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [
      "21:9",
      "16:9",
      "4:3",
      "1:1",
      "3:4",
      "9:16",
      "9:21"
    ],
    "maxRefImages": 0,
    "refRoles": [],
    "promptLimits": {
      "required": true,
      "maxLength": 10000
    },
    "params": [
      {
        "name": "seed",
        "kind": "seed",
        "min": 0,
        "max": 4294967294
      }
    ],
    "pricing": {
      "baseCostUsd": 0.06
    },
    "tags": [
      "text-to-image"
    ],
    "referenceUrl": "https://docs.bfl.ml/"
  },
  {
    "id": "bytedance/doubao-seedance-1-0-lite-i2v-250428",
    "provider": "bytedance",
    "displayName": "Seedance 1.0 Lite (i2v)",
    "description": "ByteDance Seedance 1.0 Lite image-to-video.",
    "mediaType": "video",
    "output": "video",
    "capabilities": {
      "textToImage": false,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": true,
      "imageToVideo": true
    },
    "sizes": [],
    "aspectRatios": [
      "16:9",
      "9:16",
      "1:1",
      "4:3",
      "3:4"
    ],
    "maxRefImages": 2,
    "refRoles": [
      {
        "name": "first_frame",
        "required": false,
        "min": 0,
        "max": 1
      },
      {
        "name": "last_frame",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 3000
    },
    "params": [
      {
        "name": "duration_seconds",
        "kind": "float",
        "default": 5,
        "min": 3,
        "max": 12
      },
      {
        "name": "resolution",
        "kind": "string",
        "enum": [
          "480p",
          "720p"
        ]
      }
    ],
    "pricing": {
      "baseCostUsd": 0.18
    },
    "tags": [
      "image-to-video",
      "text-to-video",
      "fast"
    ],
    "referenceUrl": "https://docs.byteplus.com/en/docs/ModelArk/"
  },
  {
    "id": "bytedance/doubao-seedance-1-0-pro-250528",
    "provider": "bytedance",
    "displayName": "Seedance 1.0 Pro",
    "description": "ByteDance Seedance 1.0 Pro text/image-to-video (first/last frame).",
    "mediaType": "video",
    "output": "video",
    "capabilities": {
      "textToImage": false,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": true,
      "imageToVideo": true
    },
    "sizes": [],
    "aspectRatios": [
      "16:9",
      "9:16",
      "1:1",
      "4:3",
      "3:4",
      "21:9"
    ],
    "maxRefImages": 2,
    "refRoles": [
      {
        "name": "first_frame",
        "required": false,
        "min": 0,
        "max": 1
      },
      {
        "name": "last_frame",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 3000
    },
    "params": [
      {
        "name": "duration_seconds",
        "kind": "float",
        "default": 5,
        "min": 3,
        "max": 12
      },
      {
        "name": "resolution",
        "kind": "string",
        "enum": [
          "480p",
          "720p",
          "1080p"
        ]
      }
    ],
    "pricing": {
      "baseCostUsd": 0.5
    },
    "tags": [
      "text-to-video",
      "image-to-video"
    ],
    "referenceUrl": "https://docs.byteplus.com/en/docs/ModelArk/"
  },
  {
    "id": "bytedance/seedream-3-0-t2i-250415",
    "provider": "bytedance",
    "displayName": "Seedream 3.0",
    "description": "ByteDance Seedream 3.0 text-to-image.",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [],
    "maxRefImages": 0,
    "refRoles": [],
    "promptLimits": {
      "required": true,
      "maxLength": 3000
    },
    "params": [
      {
        "name": "seed",
        "kind": "seed",
        "min": 0,
        "max": 2147483647
      }
    ],
    "pricing": {
      "baseCostUsd": 0.03
    },
    "tags": [
      "text-to-image"
    ],
    "referenceUrl": "https://docs.byteplus.com/en/docs/ModelArk/"
  },
  {
    "id": "bytedance/seedream-4-0-250828",
    "provider": "bytedance",
    "displayName": "Seedream 4.0",
    "description": "ByteDance Seedream 4.0 text-to-image + multi-reference edit.",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": true,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [],
    "maxRefImages": 6,
    "refRoles": [
      {
        "name": "init",
        "required": false,
        "min": 0,
        "max": 6
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 3000
    },
    "params": [
      {
        "name": "seed",
        "kind": "seed",
        "min": 0,
        "max": 2147483647
      }
    ],
    "pricing": {
      "baseCostUsd": 0.03
    },
    "tags": [
      "text-to-image",
      "image-to-image"
    ],
    "referenceUrl": "https://docs.byteplus.com/en/docs/ModelArk/"
  },
  {
    "id": "fal/auraflow",
    "provider": "fal",
    "displayName": "AuraFlow (Fal)",
    "description": "",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [],
    "maxRefImages": 0,
    "refRoles": [],
    "promptLimits": {
      "required": true,
      "maxLength": 5000
    },
    "params": [
      {
        "name": "seed",
        "kind": "seed",
        "min": 0,
        "max": 4294967294
      },
      {
        "name": "steps",
        "kind": "int",
        "default": 25,
        "min": 10,
        "max": 50
      },
      {
        "name": "guidance_scale",
        "kind": "float",
        "default": 3.5,
        "min": 0,
        "max": 10
      }
    ],
    "pricing": {
      "baseCostUsd": 0.02
    },
    "tags": [
      "text-to-image"
    ],
    "referenceUrl": "https://fal.ai/docs/documentation"
  },
  {
    "id": "fal/flux-dev",
    "provider": "fal",
    "displayName": "Flux Dev (Fal)",
    "description": "Flux Dev on Fal.",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [],
    "maxRefImages": 0,
    "refRoles": [],
    "promptLimits": {
      "required": true,
      "maxLength": 5000
    },
    "params": [
      {
        "name": "seed",
        "kind": "seed",
        "min": 0,
        "max": 4294967294
      },
      {
        "name": "guidance_scale",
        "kind": "float",
        "default": 3.5,
        "min": 0,
        "max": 10
      },
      {
        "name": "steps",
        "kind": "int",
        "default": 28,
        "min": 1,
        "max": 50
      }
    ],
    "pricing": {
      "baseCostUsd": 0.025
    },
    "tags": [
      "text-to-image"
    ],
    "referenceUrl": "https://fal.ai/docs/documentation"
  },
  {
    "id": "fal/flux-pro",
    "provider": "fal",
    "displayName": "Flux Pro (Fal)",
    "description": "Flux Pro hosted on Fal.",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [],
    "maxRefImages": 0,
    "refRoles": [],
    "promptLimits": {
      "required": true,
      "maxLength": 5000
    },
    "params": [
      {
        "name": "seed",
        "kind": "seed",
        "min": 0,
        "max": 4294967294
      },
      {
        "name": "guidance_scale",
        "kind": "float",
        "default": 3,
        "min": 1.5,
        "max": 5
      },
      {
        "name": "steps",
        "kind": "int",
        "default": 25,
        "min": 1,
        "max": 50
      }
    ],
    "pricing": {
      "baseCostUsd": 0.05
    },
    "tags": [
      "text-to-image"
    ],
    "referenceUrl": "https://fal.ai/docs/documentation"
  },
  {
    "id": "fal/flux-schnell",
    "provider": "fal",
    "displayName": "Flux Schnell (Fal)",
    "description": "Fast Flux on Fal.",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [],
    "maxRefImages": 0,
    "refRoles": [],
    "promptLimits": {
      "required": true,
      "maxLength": 5000
    },
    "params": [
      {
        "name": "seed",
        "kind": "seed",
        "min": 0,
        "max": 4294967294
      },
      {
        "name": "steps",
        "kind": "int",
        "default": 4,
        "min": 1,
        "max": 4
      }
    ],
    "pricing": {
      "baseCostUsd": 0.003
    },
    "tags": [
      "text-to-image",
      "fast"
    ],
    "referenceUrl": "https://fal.ai/docs/documentation"
  },
  {
    "id": "fal/recraft-v3",
    "provider": "fal",
    "displayName": "Recraft V3 (Fal)",
    "description": "",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [],
    "maxRefImages": 0,
    "refRoles": [],
    "promptLimits": {
      "required": true,
      "maxLength": 5000
    },
    "params": [
      {
        "name": "style",
        "kind": "string",
        "enum": [
          "realistic_image",
          "digital_illustration",
          "vector_illustration"
        ]
      }
    ],
    "pricing": {
      "baseCostUsd": 0.04
    },
    "tags": [
      "text-to-image",
      "styled"
    ],
    "referenceUrl": "https://fal.ai/docs/documentation"
  },
  {
    "id": "fal/sd35-medium",
    "provider": "fal",
    "displayName": "SD 3.5 Medium (Fal)",
    "description": "",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [],
    "maxRefImages": 0,
    "refRoles": [],
    "promptLimits": {
      "required": true,
      "maxLength": 5000
    },
    "params": [
      {
        "name": "negative_prompt",
        "kind": "string"
      },
      {
        "name": "seed",
        "kind": "seed",
        "min": 0,
        "max": 4294967294
      },
      {
        "name": "steps",
        "kind": "int",
        "default": 28,
        "min": 10,
        "max": 50
      },
      {
        "name": "guidance_scale",
        "kind": "float",
        "default": 4.5,
        "min": 0,
        "max": 10
      }
    ],
    "pricing": {
      "baseCostUsd": 0.025
    },
    "tags": [
      "text-to-image"
    ],
    "referenceUrl": "https://fal.ai/docs/documentation"
  },
  {
    "id": "fal/sdxl",
    "provider": "fal",
    "displayName": "SDXL (Fal)",
    "description": "",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [],
    "maxRefImages": 0,
    "refRoles": [],
    "promptLimits": {
      "required": true,
      "maxLength": 2000
    },
    "params": [
      {
        "name": "negative_prompt",
        "kind": "string"
      },
      {
        "name": "seed",
        "kind": "seed",
        "min": 0,
        "max": 4294967294
      },
      {
        "name": "steps",
        "kind": "int",
        "default": 50,
        "min": 10,
        "max": 100
      },
      {
        "name": "guidance_scale",
        "kind": "float",
        "default": 7.5,
        "min": 1,
        "max": 20
      }
    ],
    "pricing": {
      "baseCostUsd": 0.015
    },
    "tags": [
      "text-to-image"
    ],
    "referenceUrl": "https://fal.ai/docs/documentation"
  },
  {
    "id": "fal/video",
    "provider": "fal",
    "displayName": "Fal Video (generic)",
    "description": "",
    "mediaType": "video",
    "output": "video",
    "capabilities": {
      "textToImage": false,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": true,
      "imageToVideo": true
    },
    "sizes": [],
    "aspectRatios": [],
    "maxRefImages": 1,
    "refRoles": [
      {
        "name": "init",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 2000
    },
    "params": [
      {
        "name": "duration_seconds",
        "kind": "float",
        "min": 2,
        "max": 10
      },
      {
        "name": "seed",
        "kind": "seed",
        "min": 0,
        "max": 4294967294
      }
    ],
    "pricing": {
      "baseCostUsd": 0.2
    },
    "tags": [
      "text-to-video",
      "image-to-video"
    ],
    "referenceUrl": "https://fal.ai/docs/documentation"
  },
  {
    "id": "google/gemini-2.5-flash-image",
    "provider": "google",
    "displayName": "Gemini 2.5 Flash (image)",
    "description": "Gemini 2.5 Flash image generation.",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": true,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [
      "1:1",
      "16:9",
      "9:16",
      "4:3",
      "3:4"
    ],
    "maxRefImages": 1,
    "refRoles": [
      {
        "name": "init",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 4000
    },
    "params": [],
    "pricing": {
      "baseCostUsd": 0.02
    },
    "tags": [
      "text-to-image",
      "image-to-image"
    ],
    "referenceUrl": "https://ai.google.dev/gemini-api/docs"
  },
  {
    "id": "google/gemini-3-pro-image",
    "provider": "google",
    "displayName": "Gemini 3 Pro (image)",
    "description": "Gemini 3 Pro image generation.",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": true,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [
      "1:1",
      "16:9",
      "9:16",
      "4:3",
      "3:4",
      "21:9",
      "9:21"
    ],
    "maxRefImages": 3,
    "refRoles": [
      {
        "name": "init",
        "required": false,
        "min": 0,
        "max": 3
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 8000
    },
    "params": [],
    "pricing": {
      "baseCostUsd": 0.05
    },
    "tags": [
      "text-to-image",
      "image-to-image",
      "multi-ref"
    ],
    "referenceUrl": "https://ai.google.dev/gemini-api/docs"
  },
  {
    "id": "google/imagen-3",
    "provider": "google",
    "displayName": "Imagen 3",
    "description": "Google Imagen 3 via Gemini API.",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [
      "1:1",
      "9:16",
      "16:9",
      "3:4",
      "4:3"
    ],
    "maxRefImages": 0,
    "refRoles": [],
    "promptLimits": {
      "required": true,
      "maxLength": 4000
    },
    "params": [
      {
        "name": "negative_prompt",
        "kind": "string"
      },
      {
        "name": "seed",
        "kind": "seed",
        "min": 0,
        "max": 2147483647
      }
    ],
    "pricing": {
      "baseCostUsd": 0.04
    },
    "tags": [
      "text-to-image"
    ],
    "referenceUrl": "https://ai.google.dev/gemini-api/docs"
  },
  {
    "id": "google/veo-2.0-generate-001",
    "provider": "google",
    "displayName": "Veo 2",
    "description": "Google Veo 2 text-to-video and image-to-video.",
    "mediaType": "video",
    "output": "video",
    "capabilities": {
      "textToImage": false,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": true,
      "imageToVideo": true
    },
    "sizes": [],
    "aspectRatios": [
      "16:9",
      "9:16"
    ],
    "maxRefImages": 2,
    "refRoles": [
      {
        "name": "first_frame",
        "required": false,
        "min": 0,
        "max": 1
      },
      {
        "name": "last_frame",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 4000
    },
    "params": [
      {
        "name": "duration_seconds",
        "kind": "float",
        "default": 8,
        "min": 4,
        "max": 8
      }
    ],
    "pricing": {
      "baseCostUsd": 2.8
    },
    "tags": [
      "text-to-video",
      "image-to-video"
    ],
    "referenceUrl": "https://ai.google.dev/gemini-api/docs"
  },
  {
    "id": "google/veo-3.0-fast-generate-001",
    "provider": "google",
    "displayName": "Veo 3 Fast",
    "description": "Faster, cheaper Veo 3 variant.",
    "mediaType": "video",
    "output": "video",
    "capabilities": {
      "textToImage": false,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": true,
      "imageToVideo": true
    },
    "sizes": [],
    "aspectRatios": [
      "16:9",
      "9:16"
    ],
    "maxRefImages": 2,
    "refRoles": [
      {
        "name": "first_frame",
        "required": false,
        "min": 0,
        "max": 1
      },
      {
        "name": "last_frame",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 4000
    },
    "params": [
      {
        "name": "duration_seconds",
        "kind": "float",
        "default": 8,
        "min": 4,
        "max": 8
      },
      {
        "name": "resolution",
        "kind": "string",
        "enum": [
          "720p",
          "1080p"
        ]
      }
    ],
    "pricing": {
      "baseCostUsd": 0.8
    },
    "tags": [
      "text-to-video",
      "image-to-video",
      "fast"
    ],
    "referenceUrl": "https://ai.google.dev/gemini-api/docs"
  },
  {
    "id": "google/veo-3.0-generate-001",
    "provider": "google",
    "displayName": "Veo 3",
    "description": "Google Veo 3 text-to-video and image-to-video (with audio).",
    "mediaType": "video",
    "output": "video",
    "capabilities": {
      "textToImage": false,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": true,
      "imageToVideo": true
    },
    "sizes": [],
    "aspectRatios": [
      "16:9",
      "9:16"
    ],
    "maxRefImages": 2,
    "refRoles": [
      {
        "name": "first_frame",
        "required": false,
        "min": 0,
        "max": 1
      },
      {
        "name": "last_frame",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 4000
    },
    "params": [
      {
        "name": "duration_seconds",
        "kind": "float",
        "default": 8,
        "min": 4,
        "max": 8
      },
      {
        "name": "resolution",
        "kind": "string",
        "enum": [
          "720p",
          "1080p"
        ]
      }
    ],
    "pricing": {
      "baseCostUsd": 3.2
    },
    "tags": [
      "text-to-video",
      "image-to-video"
    ],
    "referenceUrl": "https://ai.google.dev/gemini-api/docs"
  },
  {
    "id": "google/veo-3.1-generate-preview",
    "provider": "google",
    "displayName": "Veo 3.1 (preview)",
    "description": "Veo 3.1 preview — adds reference images and richer control. Paid-tier, preview model id (subject to change).",
    "mediaType": "video",
    "output": "video",
    "capabilities": {
      "textToImage": false,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": true,
      "imageToVideo": true
    },
    "sizes": [],
    "aspectRatios": [
      "16:9",
      "9:16"
    ],
    "maxRefImages": 2,
    "refRoles": [
      {
        "name": "first_frame",
        "required": false,
        "min": 0,
        "max": 1
      },
      {
        "name": "last_frame",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 4000
    },
    "params": [
      {
        "name": "duration_seconds",
        "kind": "float",
        "default": 8,
        "min": 4,
        "max": 8
      },
      {
        "name": "resolution",
        "kind": "string",
        "enum": [
          "720p",
          "1080p",
          "4k"
        ]
      }
    ],
    "pricing": {
      "baseCostUsd": 3.2
    },
    "tags": [
      "text-to-video",
      "image-to-video",
      "preview"
    ],
    "referenceUrl": "https://ai.google.dev/gemini-api/docs"
  },
  {
    "id": "hunyuan/hunyuan-image",
    "provider": "hunyuan",
    "displayName": "Hunyuan Image",
    "description": "Tencent Hunyuan text-to-image (async SubmitHunyuanImageJob).",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": true,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [],
    "maxRefImages": 1,
    "refRoles": [
      {
        "name": "init",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 1024
    },
    "params": [
      {
        "name": "negative_prompt",
        "kind": "string"
      },
      {
        "name": "seed",
        "kind": "seed",
        "min": 0,
        "max": 2147483647
      }
    ],
    "pricing": {
      "baseCostUsd": 0.04
    },
    "tags": [
      "text-to-image",
      "image-to-image"
    ],
    "referenceUrl": "https://www.tencentcloud.com/document/product/1284/74915"
  },
  {
    "id": "hunyuan/hunyuan-video",
    "provider": "hunyuan",
    "displayName": "Hunyuan Video",
    "description": "Tencent Hunyuan image-to-video (async SubmitImageToVideoJob on vclm).",
    "mediaType": "video",
    "output": "video",
    "capabilities": {
      "textToImage": false,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": true,
      "imageToVideo": true
    },
    "sizes": [],
    "aspectRatios": [],
    "maxRefImages": 1,
    "refRoles": [
      {
        "name": "first_frame",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 2000
    },
    "params": [
      {
        "name": "resolution",
        "kind": "string",
        "enum": [
          "540p",
          "720p"
        ]
      }
    ],
    "pricing": {
      "baseCostUsd": 0.5
    },
    "tags": [
      "text-to-video",
      "image-to-video"
    ],
    "referenceUrl": "https://www.tencentcloud.com/document/product/1284/74915"
  },
  {
    "id": "ideogram/ideogram-v3",
    "provider": "ideogram",
    "displayName": "Ideogram 3.0",
    "description": "Ideogram 3.0 text-to-image with style/character reference images.",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": true,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [
      "1:1",
      "16:9",
      "9:16",
      "3:2",
      "2:3",
      "4:3",
      "3:4",
      "4:5",
      "5:4",
      "16:10",
      "10:16",
      "3:1",
      "1:3"
    ],
    "maxRefImages": 3,
    "refRoles": [
      {
        "name": "style",
        "required": false,
        "min": 0,
        "max": 3
      },
      {
        "name": "character",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 10000
    },
    "params": [
      {
        "name": "negative_prompt",
        "kind": "string"
      },
      {
        "name": "seed",
        "kind": "seed",
        "min": 0,
        "max": 2147483647
      },
      {
        "name": "style",
        "kind": "string",
        "enum": [
          "AUTO",
          "GENERAL",
          "REALISTIC",
          "DESIGN",
          "FICTION"
        ]
      }
    ],
    "pricing": {
      "baseCostUsd": 0.06
    },
    "tags": [
      "text-to-image",
      "image-to-image"
    ],
    "referenceUrl": "https://developer.ideogram.ai/"
  },
  {
    "id": "ideogram/ideogram-v3-quality",
    "provider": "ideogram",
    "displayName": "Ideogram 3.0 Quality",
    "description": "Ideogram 3.0 with QUALITY rendering speed.",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": true,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [
      "1:1",
      "16:9",
      "9:16",
      "3:2",
      "2:3",
      "4:3",
      "3:4",
      "4:5",
      "5:4",
      "16:10",
      "10:16",
      "3:1",
      "1:3"
    ],
    "maxRefImages": 3,
    "refRoles": [
      {
        "name": "style",
        "required": false,
        "min": 0,
        "max": 3
      },
      {
        "name": "character",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 10000
    },
    "params": [
      {
        "name": "negative_prompt",
        "kind": "string"
      },
      {
        "name": "seed",
        "kind": "seed",
        "min": 0,
        "max": 2147483647
      },
      {
        "name": "style",
        "kind": "string",
        "enum": [
          "AUTO",
          "GENERAL",
          "REALISTIC",
          "DESIGN",
          "FICTION"
        ]
      }
    ],
    "pricing": {
      "baseCostUsd": 0.09
    },
    "tags": [
      "text-to-image",
      "quality"
    ],
    "referenceUrl": "https://developer.ideogram.ai/"
  },
  {
    "id": "ideogram/ideogram-v3-turbo",
    "provider": "ideogram",
    "displayName": "Ideogram 3.0 Turbo",
    "description": "Ideogram 3.0 with TURBO rendering speed (faster, cheaper).",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": true,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [
      "1:1",
      "16:9",
      "9:16",
      "3:2",
      "2:3",
      "4:3",
      "3:4",
      "4:5",
      "5:4",
      "16:10",
      "10:16",
      "3:1",
      "1:3"
    ],
    "maxRefImages": 3,
    "refRoles": [
      {
        "name": "style",
        "required": false,
        "min": 0,
        "max": 3
      },
      {
        "name": "character",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 10000
    },
    "params": [
      {
        "name": "negative_prompt",
        "kind": "string"
      },
      {
        "name": "seed",
        "kind": "seed",
        "min": 0,
        "max": 2147483647
      },
      {
        "name": "style",
        "kind": "string",
        "enum": [
          "AUTO",
          "GENERAL",
          "REALISTIC",
          "DESIGN",
          "FICTION"
        ]
      }
    ],
    "pricing": {
      "baseCostUsd": 0.03
    },
    "tags": [
      "text-to-image",
      "fast"
    ],
    "referenceUrl": "https://developer.ideogram.ai/"
  },
  {
    "id": "kling/kling-v1-5",
    "provider": "kling",
    "displayName": "Kling Image v1.5",
    "description": "Kling (Kolors) v1.5 text-to-image.",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [
      "16:9",
      "9:16",
      "1:1",
      "4:3",
      "3:4",
      "3:2",
      "2:3"
    ],
    "maxRefImages": 0,
    "refRoles": [],
    "promptLimits": {
      "required": true,
      "maxLength": 2500
    },
    "params": [
      {
        "name": "negative_prompt",
        "kind": "string"
      }
    ],
    "pricing": {
      "baseCostUsd": 0.035
    },
    "tags": [
      "text-to-image"
    ],
    "referenceUrl": "https://app.klingai.com/global/dev/document-api/quickStart/productIntroduction/overview"
  },
  {
    "id": "kling/kling-v2",
    "provider": "kling",
    "displayName": "Kling Image v2",
    "description": "Kling (Kolors) text-to-image + subject reference.",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": true,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [
      "16:9",
      "9:16",
      "1:1",
      "4:3",
      "3:4",
      "3:2",
      "2:3"
    ],
    "maxRefImages": 1,
    "refRoles": [
      {
        "name": "subject",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 2500
    },
    "params": [
      {
        "name": "negative_prompt",
        "kind": "string"
      }
    ],
    "pricing": {
      "baseCostUsd": 0.04
    },
    "tags": [
      "text-to-image",
      "image-to-image"
    ],
    "referenceUrl": "https://app.klingai.com/global/dev/document-api/quickStart/productIntroduction/overview"
  },
  {
    "id": "kling/video-kling-v1-6",
    "provider": "kling",
    "displayName": "Kling Video v1.6",
    "description": "Kling v1.6 text/image-to-video.",
    "mediaType": "video",
    "output": "video",
    "capabilities": {
      "textToImage": false,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": true,
      "imageToVideo": true
    },
    "sizes": [],
    "aspectRatios": [
      "16:9",
      "9:16",
      "1:1"
    ],
    "maxRefImages": 2,
    "refRoles": [
      {
        "name": "first_frame",
        "required": false,
        "min": 0,
        "max": 1
      },
      {
        "name": "last_frame",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 2500
    },
    "params": [
      {
        "name": "negative_prompt",
        "kind": "string"
      },
      {
        "name": "duration_seconds",
        "kind": "float",
        "default": 5,
        "min": 5,
        "max": 10
      }
    ],
    "pricing": {
      "baseCostUsd": 0.5
    },
    "tags": [
      "text-to-video",
      "image-to-video"
    ],
    "referenceUrl": "https://app.klingai.com/global/dev/document-api/quickStart/productIntroduction/overview"
  },
  {
    "id": "kling/video-kling-v2-1",
    "provider": "kling",
    "displayName": "Kling Video v2.1",
    "description": "Kling v2.1 text/image-to-video (first frame + image_tail last frame).",
    "mediaType": "video",
    "output": "video",
    "capabilities": {
      "textToImage": false,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": true,
      "imageToVideo": true
    },
    "sizes": [],
    "aspectRatios": [
      "16:9",
      "9:16",
      "1:1"
    ],
    "maxRefImages": 2,
    "refRoles": [
      {
        "name": "first_frame",
        "required": false,
        "min": 0,
        "max": 1
      },
      {
        "name": "last_frame",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 2500
    },
    "params": [
      {
        "name": "negative_prompt",
        "kind": "string"
      },
      {
        "name": "duration_seconds",
        "kind": "float",
        "default": 5,
        "min": 5,
        "max": 10
      }
    ],
    "pricing": {
      "baseCostUsd": 1
    },
    "tags": [
      "text-to-video",
      "image-to-video"
    ],
    "referenceUrl": "https://app.klingai.com/global/dev/document-api/quickStart/productIntroduction/overview"
  },
  {
    "id": "leonardo/diffusion-xl",
    "provider": "leonardo",
    "displayName": "Leonardo Diffusion XL",
    "description": "Leonardo image generation (default Diffusion XL model). Add more models via providers.leonardo.model_mapping.",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": true,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [],
    "maxRefImages": 1,
    "refRoles": [
      {
        "name": "init",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 4000
    },
    "params": [
      {
        "name": "negative_prompt",
        "kind": "string"
      },
      {
        "name": "seed",
        "kind": "seed",
        "min": 0,
        "max": 2147483647
      },
      {
        "name": "strength",
        "kind": "float",
        "min": 0.1,
        "max": 0.9
      }
    ],
    "pricing": {
      "baseCostUsd": 0.02
    },
    "tags": [
      "text-to-image",
      "image-to-image"
    ],
    "referenceUrl": "https://docs.leonardo.ai/"
  },
  {
    "id": "leonardo/kling2.1",
    "provider": "leonardo",
    "displayName": "Leonardo Kling 2.1",
    "description": "Kling 2.1 served through Leonardo's first-party API.",
    "mediaType": "video",
    "output": "video",
    "capabilities": {
      "textToImage": false,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": true
    },
    "sizes": [],
    "aspectRatios": [],
    "maxRefImages": 1,
    "refRoles": [
      {
        "name": "first_frame",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 4000
    },
    "params": [
      {
        "name": "duration_seconds",
        "kind": "float",
        "default": 5,
        "min": 5,
        "max": 10
      },
      {
        "name": "resolution",
        "kind": "string",
        "enum": [
          "720p",
          "1080p"
        ]
      }
    ],
    "pricing": {
      "baseCostUsd": 1
    },
    "tags": [
      "image-to-video"
    ],
    "referenceUrl": "https://docs.leonardo.ai/"
  },
  {
    "id": "leonardo/motion2",
    "provider": "leonardo",
    "displayName": "Leonardo Motion 2.0",
    "description": "Leonardo Motion 2.0 image-to-video.",
    "mediaType": "video",
    "output": "video",
    "capabilities": {
      "textToImage": false,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": true
    },
    "sizes": [],
    "aspectRatios": [],
    "maxRefImages": 1,
    "refRoles": [
      {
        "name": "first_frame",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 4000
    },
    "params": [
      {
        "name": "duration_seconds",
        "kind": "float",
        "default": 5,
        "min": 4,
        "max": 10
      },
      {
        "name": "resolution",
        "kind": "string",
        "enum": [
          "480p",
          "720p",
          "1080p"
        ]
      }
    ],
    "pricing": {
      "baseCostUsd": 0.3
    },
    "tags": [
      "image-to-video"
    ],
    "referenceUrl": "https://docs.leonardo.ai/"
  },
  {
    "id": "leonardo/veo3",
    "provider": "leonardo",
    "displayName": "Leonardo Veo 3",
    "description": "Google Veo 3 served through Leonardo's first-party API (start-frame image-to-video).",
    "mediaType": "video",
    "output": "video",
    "capabilities": {
      "textToImage": false,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": true
    },
    "sizes": [],
    "aspectRatios": [],
    "maxRefImages": 1,
    "refRoles": [
      {
        "name": "first_frame",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 4000
    },
    "params": [
      {
        "name": "duration_seconds",
        "kind": "float",
        "default": 8,
        "min": 4,
        "max": 8
      },
      {
        "name": "resolution",
        "kind": "string",
        "enum": [
          "720p",
          "1080p"
        ]
      }
    ],
    "pricing": {
      "baseCostUsd": 2.5
    },
    "tags": [
      "image-to-video",
      "premium"
    ],
    "referenceUrl": "https://docs.leonardo.ai/"
  },
  {
    "id": "luma/dream-machine",
    "provider": "luma",
    "displayName": "Luma Dream Machine",
    "description": "",
    "mediaType": "video",
    "output": "video",
    "capabilities": {
      "textToImage": false,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": true,
      "imageToVideo": true
    },
    "sizes": [],
    "aspectRatios": [
      "1:1",
      "16:9",
      "9:16",
      "4:3",
      "3:4",
      "21:9",
      "9:21"
    ],
    "maxRefImages": 2,
    "refRoles": [
      {
        "name": "first_frame",
        "required": false,
        "min": 0,
        "max": 1
      },
      {
        "name": "last_frame",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 1000
    },
    "params": [
      {
        "name": "duration_seconds",
        "kind": "float",
        "min": 3,
        "max": 9
      }
    ],
    "pricing": {
      "baseCostUsd": 0.35
    },
    "tags": [
      "text-to-video",
      "image-to-video"
    ],
    "referenceUrl": "https://docs.lumalabs.ai/docs/api"
  },
  {
    "id": "luma/photon-1",
    "provider": "luma",
    "displayName": "Luma Photon",
    "description": "Luma Photon text-to-image with image/style/character references.",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": true,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [
      "1:1",
      "3:4",
      "4:3",
      "9:16",
      "16:9",
      "9:21",
      "21:9"
    ],
    "maxRefImages": 4,
    "refRoles": [
      {
        "name": "init",
        "required": false,
        "min": 0,
        "max": 4
      },
      {
        "name": "style",
        "required": false,
        "min": 0,
        "max": 4
      },
      {
        "name": "character",
        "required": false,
        "min": 0,
        "max": 4
      },
      {
        "name": "modify",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 1000
    },
    "params": [],
    "pricing": {
      "baseCostUsd": 0.015
    },
    "tags": [
      "text-to-image",
      "image-to-image"
    ],
    "referenceUrl": "https://docs.lumalabs.ai/docs/api"
  },
  {
    "id": "luma/photon-flash-1",
    "provider": "luma",
    "displayName": "Luma Photon Flash",
    "description": "Faster, cheaper Photon variant.",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": true,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [
      "1:1",
      "3:4",
      "4:3",
      "9:16",
      "16:9",
      "9:21",
      "21:9"
    ],
    "maxRefImages": 4,
    "refRoles": [
      {
        "name": "init",
        "required": false,
        "min": 0,
        "max": 4
      },
      {
        "name": "style",
        "required": false,
        "min": 0,
        "max": 4
      },
      {
        "name": "character",
        "required": false,
        "min": 0,
        "max": 4
      },
      {
        "name": "modify",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 1000
    },
    "params": [],
    "pricing": {
      "baseCostUsd": 0.002
    },
    "tags": [
      "text-to-image",
      "image-to-image",
      "fast"
    ],
    "referenceUrl": "https://docs.lumalabs.ai/docs/api"
  },
  {
    "id": "luma/ray-2",
    "provider": "luma",
    "displayName": "Luma Ray 2",
    "description": "",
    "mediaType": "video",
    "output": "video",
    "capabilities": {
      "textToImage": false,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": true,
      "imageToVideo": true
    },
    "sizes": [],
    "aspectRatios": [
      "1:1",
      "16:9",
      "9:16",
      "4:3",
      "3:4",
      "21:9",
      "9:21"
    ],
    "maxRefImages": 2,
    "refRoles": [
      {
        "name": "first_frame",
        "required": false,
        "min": 0,
        "max": 1
      },
      {
        "name": "last_frame",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 1000
    },
    "params": [
      {
        "name": "duration_seconds",
        "kind": "float",
        "min": 5,
        "max": 9
      },
      {
        "name": "resolution",
        "kind": "string",
        "enum": [
          "540p",
          "720p",
          "1080p"
        ]
      }
    ],
    "pricing": {
      "baseCostUsd": 0.4
    },
    "tags": [
      "text-to-video",
      "image-to-video"
    ],
    "referenceUrl": "https://docs.lumalabs.ai/docs/api"
  },
  {
    "id": "luma/ray-3",
    "provider": "luma",
    "displayName": "Luma Ray 3",
    "description": "",
    "mediaType": "video",
    "output": "video",
    "capabilities": {
      "textToImage": false,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": true,
      "imageToVideo": true
    },
    "sizes": [],
    "aspectRatios": [
      "1:1",
      "16:9",
      "9:16",
      "4:3",
      "3:4",
      "21:9",
      "9:21"
    ],
    "maxRefImages": 2,
    "refRoles": [
      {
        "name": "first_frame",
        "required": false,
        "min": 0,
        "max": 1
      },
      {
        "name": "last_frame",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 1000
    },
    "params": [
      {
        "name": "duration_seconds",
        "kind": "float",
        "min": 5,
        "max": 9
      },
      {
        "name": "resolution",
        "kind": "string",
        "enum": [
          "720p",
          "1080p",
          "4k"
        ]
      }
    ],
    "pricing": {
      "baseCostUsd": 0.5
    },
    "tags": [
      "text-to-video",
      "image-to-video",
      "premium"
    ],
    "referenceUrl": "https://docs.lumalabs.ai/docs/api"
  },
  {
    "id": "luma/ray-flash-2",
    "provider": "luma",
    "displayName": "Luma Ray Flash 2",
    "description": "",
    "mediaType": "video",
    "output": "video",
    "capabilities": {
      "textToImage": false,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": true,
      "imageToVideo": true
    },
    "sizes": [],
    "aspectRatios": [
      "1:1",
      "16:9",
      "9:16",
      "4:3",
      "3:4"
    ],
    "maxRefImages": 2,
    "refRoles": [
      {
        "name": "first_frame",
        "required": false,
        "min": 0,
        "max": 1
      },
      {
        "name": "last_frame",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 1000
    },
    "params": [
      {
        "name": "duration_seconds",
        "kind": "float",
        "min": 5,
        "max": 9
      }
    ],
    "pricing": {
      "baseCostUsd": 0.2
    },
    "tags": [
      "text-to-video",
      "image-to-video",
      "fast"
    ],
    "referenceUrl": "https://docs.lumalabs.ai/docs/api"
  },
  {
    "id": "luma/ray-hdr-3",
    "provider": "luma",
    "displayName": "Luma Ray HDR 3",
    "description": "",
    "mediaType": "video",
    "output": "video",
    "capabilities": {
      "textToImage": false,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": true,
      "imageToVideo": true
    },
    "sizes": [],
    "aspectRatios": [
      "16:9",
      "9:16",
      "21:9"
    ],
    "maxRefImages": 2,
    "refRoles": [
      {
        "name": "first_frame",
        "required": false,
        "min": 0,
        "max": 1
      },
      {
        "name": "last_frame",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 1000
    },
    "params": [
      {
        "name": "duration_seconds",
        "kind": "float",
        "min": 5,
        "max": 9
      },
      {
        "name": "resolution",
        "kind": "string",
        "enum": [
          "1080p",
          "4k"
        ]
      }
    ],
    "pricing": {
      "baseCostUsd": 0.65
    },
    "tags": [
      "text-to-video",
      "image-to-video",
      "hdr"
    ],
    "referenceUrl": "https://docs.lumalabs.ai/docs/api"
  },
  {
    "id": "minimax/image-01",
    "provider": "minimax",
    "displayName": "MiniMax image-01",
    "description": "MiniMax image-01 text-to-image with subject reference.",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": true,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [
      "1:1",
      "16:9",
      "4:3",
      "3:2",
      "2:3",
      "3:4",
      "9:16",
      "21:9"
    ],
    "maxRefImages": 1,
    "refRoles": [
      {
        "name": "subject",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 1500
    },
    "params": [],
    "pricing": {
      "baseCostUsd": 0.01
    },
    "tags": [
      "text-to-image",
      "image-to-image"
    ],
    "referenceUrl": "https://platform.minimax.io/docs"
  },
  {
    "id": "minimax/MiniMax-Hailuo-02",
    "provider": "minimax",
    "displayName": "MiniMax Hailuo 02",
    "description": "Hailuo 02 text-to-video and image-to-video (first/last frame).",
    "mediaType": "video",
    "output": "video",
    "capabilities": {
      "textToImage": false,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": true,
      "imageToVideo": true
    },
    "sizes": [],
    "aspectRatios": [],
    "maxRefImages": 2,
    "refRoles": [
      {
        "name": "first_frame",
        "required": false,
        "min": 0,
        "max": 1
      },
      {
        "name": "last_frame",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 2000
    },
    "params": [
      {
        "name": "duration_seconds",
        "kind": "float",
        "default": 6,
        "min": 6,
        "max": 10
      },
      {
        "name": "resolution",
        "kind": "string",
        "enum": [
          "512P",
          "768P",
          "1080P"
        ]
      }
    ],
    "pricing": {
      "baseCostUsd": 0.43
    },
    "tags": [
      "text-to-video",
      "image-to-video"
    ],
    "referenceUrl": "https://platform.minimax.io/docs"
  },
  {
    "id": "minimax/MiniMax-Hailuo-2.3",
    "provider": "minimax",
    "displayName": "MiniMax Hailuo 2.3",
    "description": "Hailuo 2.3 text-to-video and image-to-video.",
    "mediaType": "video",
    "output": "video",
    "capabilities": {
      "textToImage": false,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": true,
      "imageToVideo": true
    },
    "sizes": [],
    "aspectRatios": [],
    "maxRefImages": 2,
    "refRoles": [
      {
        "name": "first_frame",
        "required": false,
        "min": 0,
        "max": 1
      },
      {
        "name": "last_frame",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 2000
    },
    "params": [
      {
        "name": "duration_seconds",
        "kind": "float",
        "default": 6,
        "min": 6,
        "max": 10
      },
      {
        "name": "resolution",
        "kind": "string",
        "enum": [
          "768P",
          "1080P"
        ]
      }
    ],
    "pricing": {
      "baseCostUsd": 0.49
    },
    "tags": [
      "text-to-video",
      "image-to-video"
    ],
    "referenceUrl": "https://platform.minimax.io/docs"
  },
  {
    "id": "minimax/S2V-01",
    "provider": "minimax",
    "displayName": "MiniMax S2V-01",
    "description": "Subject-reference video (character consistency from a face photo).",
    "mediaType": "video",
    "output": "video",
    "capabilities": {
      "textToImage": false,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": true,
      "imageToVideo": true
    },
    "sizes": [],
    "aspectRatios": [],
    "maxRefImages": 1,
    "refRoles": [
      {
        "name": "subject",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 2000
    },
    "params": [
      {
        "name": "duration_seconds",
        "kind": "float",
        "default": 6,
        "min": 6,
        "max": 6
      }
    ],
    "pricing": {
      "baseCostUsd": 0.65
    },
    "tags": [
      "text-to-video",
      "subject-reference"
    ],
    "referenceUrl": "https://platform.minimax.io/docs"
  },
  {
    "id": "minimax/T2V-01-Director",
    "provider": "minimax",
    "displayName": "MiniMax T2V-01 Director",
    "description": "Text-to-video with camera-movement instructions.",
    "mediaType": "video",
    "output": "video",
    "capabilities": {
      "textToImage": false,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": true,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [],
    "maxRefImages": 0,
    "refRoles": [],
    "promptLimits": {
      "required": true,
      "maxLength": 2000
    },
    "params": [
      {
        "name": "duration_seconds",
        "kind": "float",
        "default": 6,
        "min": 6,
        "max": 6
      }
    ],
    "pricing": {
      "baseCostUsd": 0.43
    },
    "tags": [
      "text-to-video"
    ],
    "referenceUrl": "https://platform.minimax.io/docs"
  },
  {
    "id": "openai/dall-e-2",
    "provider": "openai",
    "displayName": "DALL-E 2",
    "description": "OpenAI's older text-to-image model. Supports edits.",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": true,
      "inpainting": true,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [
      "256x256",
      "512x512",
      "1024x1024"
    ],
    "aspectRatios": [],
    "maxRefImages": 2,
    "refRoles": [
      {
        "name": "init",
        "required": false,
        "min": 0,
        "max": 1
      },
      {
        "name": "mask",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 1000
    },
    "params": [],
    "pricing": {
      "baseCostUsd": 0.02
    },
    "tags": [
      "text-to-image",
      "image-to-image",
      "inpainting"
    ],
    "referenceUrl": "https://platform.openai.com/docs/guides/image-generation"
  },
  {
    "id": "openai/dall-e-3",
    "provider": "openai",
    "displayName": "DALL-E 3",
    "description": "OpenAI's high-quality text-to-image model.",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [
      "1024x1024",
      "1792x1024",
      "1024x1792"
    ],
    "aspectRatios": [],
    "maxRefImages": 0,
    "refRoles": [],
    "promptLimits": {
      "required": true,
      "maxLength": 4000
    },
    "params": [
      {
        "name": "quality",
        "kind": "string",
        "enum": [
          "standard",
          "hd"
        ],
        "default": "standard"
      },
      {
        "name": "style",
        "kind": "string",
        "enum": [
          "vivid",
          "natural"
        ],
        "default": "vivid"
      }
    ],
    "pricing": {
      "baseCostUsd": 0.04
    },
    "tags": [
      "text-to-image"
    ],
    "referenceUrl": "https://platform.openai.com/docs/guides/image-generation"
  },
  {
    "id": "openai/sora",
    "provider": "openai",
    "displayName": "Sora 2",
    "description": "OpenAI Sora 2 text-to-video and image-to-video (maps to the `sora-2` model).",
    "mediaType": "video",
    "output": "video",
    "capabilities": {
      "textToImage": false,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": true,
      "imageToVideo": true
    },
    "sizes": [],
    "aspectRatios": [
      "16:9",
      "9:16"
    ],
    "maxRefImages": 1,
    "refRoles": [
      {
        "name": "init",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 4000
    },
    "params": [
      {
        "name": "duration_seconds",
        "kind": "float",
        "default": 4,
        "min": 4,
        "max": 12
      },
      {
        "name": "resolution",
        "kind": "string",
        "enum": [
          "720p"
        ],
        "default": "720p"
      }
    ],
    "pricing": {
      "baseCostUsd": 0.5
    },
    "tags": [
      "text-to-video",
      "image-to-video"
    ],
    "referenceUrl": "https://platform.openai.com/docs/guides/image-generation"
  },
  {
    "id": "openai/sora-2-pro",
    "provider": "openai",
    "displayName": "Sora 2 Pro",
    "description": "Higher-fidelity Sora 2 Pro (maps to the `sora-2-pro` model); adds 1080p sizes.",
    "mediaType": "video",
    "output": "video",
    "capabilities": {
      "textToImage": false,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": true,
      "imageToVideo": true
    },
    "sizes": [],
    "aspectRatios": [
      "16:9",
      "9:16"
    ],
    "maxRefImages": 1,
    "refRoles": [
      {
        "name": "init",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 4000
    },
    "params": [
      {
        "name": "duration_seconds",
        "kind": "float",
        "default": 4,
        "min": 4,
        "max": 12
      },
      {
        "name": "resolution",
        "kind": "string",
        "enum": [
          "720p",
          "1080p"
        ],
        "default": "1080p"
      }
    ],
    "pricing": {
      "baseCostUsd": 1
    },
    "tags": [
      "text-to-video",
      "image-to-video",
      "premium"
    ],
    "referenceUrl": "https://platform.openai.com/docs/guides/image-generation"
  },
  {
    "id": "pixverse/v3.5",
    "provider": "pixverse",
    "displayName": "PixVerse v3.5",
    "description": "PixVerse v3.5 text/image-to-video + transition.",
    "mediaType": "video",
    "output": "video",
    "capabilities": {
      "textToImage": false,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": true,
      "imageToVideo": true
    },
    "sizes": [],
    "aspectRatios": [
      "16:9",
      "4:3",
      "1:1",
      "3:4",
      "9:16"
    ],
    "maxRefImages": 2,
    "refRoles": [
      {
        "name": "first_frame",
        "required": false,
        "min": 0,
        "max": 1
      },
      {
        "name": "last_frame",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 5000
    },
    "params": [
      {
        "name": "seed",
        "kind": "seed",
        "min": 0,
        "max": 2147483647
      },
      {
        "name": "duration_seconds",
        "kind": "float",
        "default": 5,
        "min": 5,
        "max": 8
      },
      {
        "name": "resolution",
        "kind": "string",
        "enum": [
          "360p",
          "540p",
          "720p",
          "1080p"
        ]
      }
    ],
    "pricing": {
      "baseCostUsd": 0.3
    },
    "tags": [
      "text-to-video",
      "image-to-video"
    ],
    "referenceUrl": "https://docs.platform.pixverse.ai/"
  },
  {
    "id": "pixverse/v4.5",
    "provider": "pixverse",
    "displayName": "PixVerse v4.5",
    "description": "PixVerse v4.5 text/image-to-video + first/last-frame transition.",
    "mediaType": "video",
    "output": "video",
    "capabilities": {
      "textToImage": false,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": true,
      "imageToVideo": true
    },
    "sizes": [],
    "aspectRatios": [
      "16:9",
      "4:3",
      "1:1",
      "3:4",
      "9:16"
    ],
    "maxRefImages": 2,
    "refRoles": [
      {
        "name": "first_frame",
        "required": false,
        "min": 0,
        "max": 1
      },
      {
        "name": "last_frame",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 5000
    },
    "params": [
      {
        "name": "seed",
        "kind": "seed",
        "min": 0,
        "max": 2147483647
      },
      {
        "name": "duration_seconds",
        "kind": "float",
        "default": 5,
        "min": 5,
        "max": 8
      },
      {
        "name": "resolution",
        "kind": "string",
        "enum": [
          "360p",
          "540p",
          "720p",
          "1080p"
        ]
      }
    ],
    "pricing": {
      "baseCostUsd": 0.45
    },
    "tags": [
      "text-to-video",
      "image-to-video"
    ],
    "referenceUrl": "https://docs.platform.pixverse.ai/"
  },
  {
    "id": "pixverse/v5",
    "provider": "pixverse",
    "displayName": "PixVerse v5",
    "description": "PixVerse v5 text/image-to-video.",
    "mediaType": "video",
    "output": "video",
    "capabilities": {
      "textToImage": false,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": true,
      "imageToVideo": true
    },
    "sizes": [],
    "aspectRatios": [
      "16:9",
      "4:3",
      "1:1",
      "3:4",
      "9:16"
    ],
    "maxRefImages": 2,
    "refRoles": [
      {
        "name": "first_frame",
        "required": false,
        "min": 0,
        "max": 1
      },
      {
        "name": "last_frame",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 5000
    },
    "params": [
      {
        "name": "seed",
        "kind": "seed",
        "min": 0,
        "max": 2147483647
      },
      {
        "name": "duration_seconds",
        "kind": "float",
        "default": 5,
        "min": 5,
        "max": 8
      },
      {
        "name": "resolution",
        "kind": "string",
        "enum": [
          "360p",
          "540p",
          "720p",
          "1080p"
        ]
      }
    ],
    "pricing": {
      "baseCostUsd": 0.45
    },
    "tags": [
      "text-to-video",
      "image-to-video"
    ],
    "referenceUrl": "https://docs.platform.pixverse.ai/"
  },
  {
    "id": "recraft/recraftv2",
    "provider": "recraft",
    "displayName": "Recraft V2",
    "description": "Recraft V2 raster image generation.",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [],
    "maxRefImages": 0,
    "refRoles": [],
    "promptLimits": {
      "required": true,
      "maxLength": 1000
    },
    "params": [
      {
        "name": "style",
        "kind": "string",
        "enum": [
          "realistic_image",
          "digital_illustration",
          "vector_illustration",
          "icon",
          "any"
        ],
        "default": "realistic_image"
      }
    ],
    "pricing": {
      "baseCostUsd": 0.022
    },
    "tags": [
      "text-to-image"
    ],
    "referenceUrl": "https://www.recraft.ai/docs/api-reference/getting-started"
  },
  {
    "id": "recraft/recraftv3",
    "provider": "recraft",
    "displayName": "Recraft V3",
    "description": "Recraft V3 raster image generation.",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [],
    "maxRefImages": 0,
    "refRoles": [],
    "promptLimits": {
      "required": true,
      "maxLength": 1000
    },
    "params": [
      {
        "name": "negative_prompt",
        "kind": "string"
      },
      {
        "name": "style",
        "kind": "string",
        "enum": [
          "realistic_image",
          "digital_illustration",
          "vector_illustration",
          "icon",
          "any"
        ],
        "default": "realistic_image"
      }
    ],
    "pricing": {
      "baseCostUsd": 0.04
    },
    "tags": [
      "text-to-image"
    ],
    "referenceUrl": "https://www.recraft.ai/docs/api-reference/getting-started"
  },
  {
    "id": "recraft/recraftv3_vector",
    "provider": "recraft",
    "displayName": "Recraft V3 Vector",
    "description": "Recraft V3 vector (SVG) image generation.",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [],
    "maxRefImages": 0,
    "refRoles": [],
    "promptLimits": {
      "required": true,
      "maxLength": 1000
    },
    "params": [
      {
        "name": "negative_prompt",
        "kind": "string"
      },
      {
        "name": "style",
        "kind": "string",
        "enum": [
          "vector_illustration",
          "icon"
        ],
        "default": "vector_illustration"
      }
    ],
    "pricing": {
      "baseCostUsd": 0.08
    },
    "tags": [
      "text-to-image",
      "vector"
    ],
    "referenceUrl": "https://www.recraft.ai/docs/api-reference/getting-started"
  },
  {
    "id": "recraft/recraftv4_1",
    "provider": "recraft",
    "displayName": "Recraft V4.1",
    "description": "Recraft V4.1 raster image generation (current default).",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [],
    "maxRefImages": 0,
    "refRoles": [],
    "promptLimits": {
      "required": true,
      "maxLength": 1000
    },
    "params": [
      {
        "name": "negative_prompt",
        "kind": "string"
      },
      {
        "name": "style",
        "kind": "string",
        "enum": [
          "realistic_image",
          "digital_illustration",
          "vector_illustration",
          "icon",
          "any"
        ],
        "default": "realistic_image"
      }
    ],
    "pricing": {
      "baseCostUsd": 0.04
    },
    "tags": [
      "text-to-image"
    ],
    "referenceUrl": "https://www.recraft.ai/docs/api-reference/getting-started"
  },
  {
    "id": "recraft/recraftv4_1_pro",
    "provider": "recraft",
    "displayName": "Recraft V4.1 Pro",
    "description": "Recraft V4.1 Pro raster image generation.",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [],
    "maxRefImages": 0,
    "refRoles": [],
    "promptLimits": {
      "required": true,
      "maxLength": 1000
    },
    "params": [
      {
        "name": "negative_prompt",
        "kind": "string"
      },
      {
        "name": "style",
        "kind": "string",
        "enum": [
          "realistic_image",
          "digital_illustration",
          "vector_illustration",
          "icon",
          "any"
        ],
        "default": "realistic_image"
      }
    ],
    "pricing": {
      "baseCostUsd": 0.25
    },
    "tags": [
      "text-to-image"
    ],
    "referenceUrl": "https://www.recraft.ai/docs/api-reference/getting-started"
  },
  {
    "id": "replicate/flux-dev",
    "provider": "replicate",
    "displayName": "Flux Dev",
    "description": "Flux Dev — open weights via Replicate.",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": true,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [
      "1:1",
      "16:9",
      "21:9",
      "2:3",
      "3:2",
      "4:5",
      "5:4",
      "9:16",
      "9:21",
      "3:4",
      "4:3"
    ],
    "maxRefImages": 1,
    "refRoles": [
      {
        "name": "init",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 5000
    },
    "params": [
      {
        "name": "seed",
        "kind": "seed",
        "min": 0,
        "max": 4294967294
      },
      {
        "name": "guidance_scale",
        "kind": "float",
        "default": 3.5,
        "min": 0,
        "max": 10
      },
      {
        "name": "steps",
        "kind": "int",
        "default": 28,
        "min": 1,
        "max": 50
      }
    ],
    "pricing": {
      "baseCostUsd": 0.025
    },
    "tags": [
      "text-to-image",
      "image-to-image"
    ],
    "referenceUrl": "https://replicate.com/docs/reference/http"
  },
  {
    "id": "replicate/flux-pro",
    "provider": "replicate",
    "displayName": "Flux Pro",
    "description": "Black Forest Labs Flux Pro via Replicate.",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [
      "1:1",
      "16:9",
      "21:9",
      "2:3",
      "3:2",
      "4:5",
      "5:4",
      "9:16",
      "9:21",
      "3:4",
      "4:3"
    ],
    "maxRefImages": 0,
    "refRoles": [],
    "promptLimits": {
      "required": true,
      "maxLength": 5000
    },
    "params": [
      {
        "name": "seed",
        "kind": "seed",
        "min": 0,
        "max": 4294967294
      },
      {
        "name": "guidance_scale",
        "kind": "float",
        "default": 3,
        "min": 1.5,
        "max": 5
      },
      {
        "name": "steps",
        "kind": "int",
        "default": 25,
        "min": 1,
        "max": 50
      }
    ],
    "pricing": {
      "baseCostUsd": 0.055
    },
    "tags": [
      "text-to-image",
      "premium"
    ],
    "referenceUrl": "https://replicate.com/docs/reference/http"
  },
  {
    "id": "replicate/flux-schnell",
    "provider": "replicate",
    "displayName": "Flux Schnell",
    "description": "Fastest Flux variant.",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [
      "1:1",
      "16:9",
      "21:9",
      "2:3",
      "3:2",
      "4:5",
      "5:4",
      "9:16",
      "9:21",
      "3:4",
      "4:3"
    ],
    "maxRefImages": 0,
    "refRoles": [],
    "promptLimits": {
      "required": true,
      "maxLength": 5000
    },
    "params": [
      {
        "name": "seed",
        "kind": "seed",
        "min": 0,
        "max": 4294967294
      },
      {
        "name": "steps",
        "kind": "int",
        "default": 4,
        "min": 1,
        "max": 4
      }
    ],
    "pricing": {
      "baseCostUsd": 0.003
    },
    "tags": [
      "text-to-image",
      "fast"
    ],
    "referenceUrl": "https://replicate.com/docs/reference/http"
  },
  {
    "id": "replicate/sd3",
    "provider": "replicate",
    "displayName": "SD3 on Replicate",
    "description": "SD3 hosted on Replicate.",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [
      "1:1",
      "16:9",
      "9:16",
      "21:9",
      "9:21",
      "2:3",
      "3:2",
      "4:5",
      "5:4"
    ],
    "maxRefImages": 0,
    "refRoles": [],
    "promptLimits": {
      "required": true,
      "maxLength": 5000
    },
    "params": [
      {
        "name": "negative_prompt",
        "kind": "string"
      },
      {
        "name": "seed",
        "kind": "seed",
        "min": 0,
        "max": 4294967294
      },
      {
        "name": "steps",
        "kind": "int",
        "default": 28,
        "min": 10,
        "max": 50
      },
      {
        "name": "guidance_scale",
        "kind": "float",
        "default": 4.5,
        "min": 0,
        "max": 10
      }
    ],
    "pricing": {
      "baseCostUsd": 0.035
    },
    "tags": [
      "text-to-image"
    ],
    "referenceUrl": "https://replicate.com/docs/reference/http"
  },
  {
    "id": "replicate/sdxl",
    "provider": "replicate",
    "displayName": "SDXL on Replicate",
    "description": "SDXL hosted on Replicate.",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": true,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [],
    "maxRefImages": 1,
    "refRoles": [
      {
        "name": "init",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 2000
    },
    "params": [
      {
        "name": "negative_prompt",
        "kind": "string"
      },
      {
        "name": "seed",
        "kind": "seed",
        "min": 0,
        "max": 4294967294
      },
      {
        "name": "steps",
        "kind": "int",
        "default": 50,
        "min": 10,
        "max": 100
      },
      {
        "name": "guidance_scale",
        "kind": "float",
        "default": 7.5,
        "min": 1,
        "max": 20
      }
    ],
    "pricing": {
      "baseCostUsd": 0.012
    },
    "tags": [
      "text-to-image",
      "image-to-image"
    ],
    "referenceUrl": "https://replicate.com/docs/reference/http"
  },
  {
    "id": "replicate/video",
    "provider": "replicate",
    "displayName": "Replicate Video (generic)",
    "description": "Generic Replicate video endpoint.",
    "mediaType": "video",
    "output": "video",
    "capabilities": {
      "textToImage": false,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": true,
      "imageToVideo": true
    },
    "sizes": [],
    "aspectRatios": [],
    "maxRefImages": 1,
    "refRoles": [
      {
        "name": "init",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 2000
    },
    "params": [
      {
        "name": "duration_seconds",
        "kind": "float",
        "min": 2,
        "max": 10
      },
      {
        "name": "seed",
        "kind": "seed",
        "min": 0,
        "max": 4294967294
      }
    ],
    "pricing": {
      "baseCostUsd": 0.3
    },
    "tags": [
      "text-to-video",
      "image-to-video"
    ],
    "referenceUrl": "https://replicate.com/docs/reference/http"
  },
  {
    "id": "runway/gen-3",
    "provider": "runway",
    "displayName": "Runway Gen-3",
    "description": "Runway Gen-3.",
    "mediaType": "video",
    "output": "video",
    "capabilities": {
      "textToImage": false,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": true,
      "imageToVideo": true
    },
    "sizes": [],
    "aspectRatios": [],
    "maxRefImages": 1,
    "refRoles": [
      {
        "name": "init",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 1000
    },
    "params": [
      {
        "name": "duration_seconds",
        "kind": "int",
        "default": 5,
        "min": 5,
        "max": 10
      },
      {
        "name": "seed",
        "kind": "seed",
        "min": 0,
        "max": 4294967294
      }
    ],
    "pricing": {
      "baseCostUsd": 0.5
    },
    "tags": [
      "text-to-video",
      "image-to-video"
    ],
    "referenceUrl": "https://docs.dev.runwayml.com/"
  },
  {
    "id": "runway/gen-3-turbo",
    "provider": "runway",
    "displayName": "Runway Gen-3 Turbo",
    "description": "",
    "mediaType": "video",
    "output": "video",
    "capabilities": {
      "textToImage": false,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": true,
      "imageToVideo": true
    },
    "sizes": [],
    "aspectRatios": [],
    "maxRefImages": 1,
    "refRoles": [
      {
        "name": "init",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 1000
    },
    "params": [
      {
        "name": "duration_seconds",
        "kind": "int",
        "default": 5,
        "min": 5,
        "max": 10
      },
      {
        "name": "seed",
        "kind": "seed",
        "min": 0,
        "max": 4294967294
      }
    ],
    "pricing": {
      "baseCostUsd": 0.25
    },
    "tags": [
      "text-to-video",
      "image-to-video",
      "fast"
    ],
    "referenceUrl": "https://docs.dev.runwayml.com/"
  },
  {
    "id": "runway/gen4_image",
    "provider": "runway",
    "displayName": "Runway Gen-4 Image",
    "description": "Runway Gen-4 text-to-image with @tag reference images.",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": true,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [
      "16:9",
      "9:16",
      "1:1",
      "4:3",
      "3:4",
      "21:9",
      "3:2",
      "2:3"
    ],
    "maxRefImages": 3,
    "refRoles": [
      {
        "name": "init",
        "required": false,
        "min": 0,
        "max": 3
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 5500
    },
    "params": [
      {
        "name": "seed",
        "kind": "seed",
        "min": 0,
        "max": 4294967294
      }
    ],
    "pricing": {
      "baseCostUsd": 0.08
    },
    "tags": [
      "text-to-image",
      "image-to-image"
    ],
    "referenceUrl": "https://docs.dev.runwayml.com/"
  },
  {
    "id": "runway/gen4_image_turbo",
    "provider": "runway",
    "displayName": "Runway Gen-4 Image Turbo",
    "description": "Faster, cheaper Gen-4 image (requires at least one reference image).",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": true,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [
      "16:9",
      "9:16",
      "1:1",
      "4:3",
      "3:4",
      "21:9",
      "3:2",
      "2:3"
    ],
    "maxRefImages": 3,
    "refRoles": [
      {
        "name": "init",
        "required": false,
        "min": 1,
        "max": 3
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 5500
    },
    "params": [
      {
        "name": "seed",
        "kind": "seed",
        "min": 0,
        "max": 4294967294
      }
    ],
    "pricing": {
      "baseCostUsd": 0.02
    },
    "tags": [
      "text-to-image",
      "image-to-image",
      "fast"
    ],
    "referenceUrl": "https://docs.dev.runwayml.com/"
  },
  {
    "id": "stability/core",
    "provider": "stability",
    "displayName": "Stable Image Core",
    "description": "Fast, affordable image generation.",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [
      "1:1",
      "16:9",
      "21:9",
      "2:3",
      "3:2",
      "4:5",
      "5:4",
      "9:16",
      "9:21"
    ],
    "maxRefImages": 0,
    "refRoles": [],
    "promptLimits": {
      "required": true,
      "maxLength": 10000
    },
    "params": [
      {
        "name": "negative_prompt",
        "kind": "string"
      },
      {
        "name": "seed",
        "kind": "seed",
        "min": 0,
        "max": 4294967294
      },
      {
        "name": "style",
        "kind": "string",
        "enum": [
          "3d-model",
          "analog-film",
          "anime",
          "cinematic",
          "comic-book",
          "digital-art",
          "enhance",
          "fantasy-art",
          "isometric",
          "line-art",
          "low-poly",
          "modeling-compound",
          "neon-punk",
          "origami",
          "photographic",
          "pixel-art",
          "tile-texture"
        ]
      }
    ],
    "pricing": {
      "baseCostUsd": 0.03
    },
    "tags": [
      "text-to-image",
      "fast",
      "affordable"
    ],
    "referenceUrl": "https://platform.stability.ai/docs/api-reference"
  },
  {
    "id": "stability/sd3-large",
    "provider": "stability",
    "displayName": "Stable Diffusion 3 Large",
    "description": "Latest Stability AI model with excellent prompt adherence.",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": true,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [
      "1:1",
      "16:9",
      "9:16",
      "3:2",
      "2:3",
      "4:5",
      "5:4",
      "21:9",
      "9:21"
    ],
    "maxRefImages": 1,
    "refRoles": [
      {
        "name": "init",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 10000
    },
    "params": [
      {
        "name": "negative_prompt",
        "kind": "string"
      },
      {
        "name": "seed",
        "kind": "seed",
        "min": 0,
        "max": 4294967294
      },
      {
        "name": "strength",
        "kind": "float",
        "min": 0,
        "max": 1
      }
    ],
    "pricing": {
      "baseCostUsd": 0.065
    },
    "tags": [
      "text-to-image",
      "image-to-image"
    ],
    "referenceUrl": "https://platform.stability.ai/docs/api-reference"
  },
  {
    "id": "stability/sd3-turbo",
    "provider": "stability",
    "displayName": "Stable Diffusion 3 Turbo",
    "description": "Faster, cheaper SD3 variant.",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [
      "1:1"
    ],
    "maxRefImages": 0,
    "refRoles": [],
    "promptLimits": {
      "required": true,
      "maxLength": 10000
    },
    "params": [
      {
        "name": "negative_prompt",
        "kind": "string"
      },
      {
        "name": "seed",
        "kind": "seed",
        "min": 0,
        "max": 4294967294
      }
    ],
    "pricing": {
      "baseCostUsd": 0.04
    },
    "tags": [
      "text-to-image",
      "fast"
    ],
    "referenceUrl": "https://platform.stability.ai/docs/api-reference"
  },
  {
    "id": "stability/sdxl",
    "provider": "stability",
    "displayName": "Stable Diffusion XL",
    "description": "High-quality general purpose image generation.",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": true,
      "inpainting": true,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [
      "512x512",
      "1024x1024"
    ],
    "aspectRatios": [],
    "maxRefImages": 2,
    "refRoles": [
      {
        "name": "init",
        "required": false,
        "min": 0,
        "max": 1
      },
      {
        "name": "mask",
        "required": false,
        "min": 0,
        "max": 1
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 2000
    },
    "params": [
      {
        "name": "negative_prompt",
        "kind": "string"
      },
      {
        "name": "seed",
        "kind": "seed",
        "min": 0,
        "max": 4294967294
      },
      {
        "name": "steps",
        "kind": "int",
        "default": 30,
        "min": 10,
        "max": 50
      },
      {
        "name": "guidance_scale",
        "kind": "float",
        "default": 7,
        "min": 0,
        "max": 35
      }
    ],
    "pricing": {
      "baseCostUsd": 0.002
    },
    "tags": [
      "text-to-image",
      "image-to-image",
      "inpainting"
    ],
    "referenceUrl": "https://platform.stability.ai/docs/api-reference"
  },
  {
    "id": "stability/ultra",
    "provider": "stability",
    "displayName": "Stable Image Ultra",
    "description": "Highest-quality Stability generation.",
    "mediaType": "image",
    "output": "image",
    "capabilities": {
      "textToImage": true,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": false,
      "imageToVideo": false
    },
    "sizes": [],
    "aspectRatios": [
      "1:1",
      "16:9",
      "21:9",
      "2:3",
      "3:2",
      "4:5",
      "5:4",
      "9:16",
      "9:21"
    ],
    "maxRefImages": 0,
    "refRoles": [],
    "promptLimits": {
      "required": true,
      "maxLength": 10000
    },
    "params": [
      {
        "name": "negative_prompt",
        "kind": "string"
      },
      {
        "name": "seed",
        "kind": "seed",
        "min": 0,
        "max": 4294967294
      }
    ],
    "pricing": {
      "baseCostUsd": 0.08
    },
    "tags": [
      "text-to-image",
      "premium",
      "photorealistic"
    ],
    "referenceUrl": "https://platform.stability.ai/docs/api-reference"
  },
  {
    "id": "vidu/vidu2.0",
    "provider": "vidu",
    "displayName": "Vidu 2.0",
    "description": "Vidu 2.0 text/image/reference to video.",
    "mediaType": "video",
    "output": "video",
    "capabilities": {
      "textToImage": false,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": true,
      "imageToVideo": true
    },
    "sizes": [],
    "aspectRatios": [
      "16:9",
      "9:16",
      "1:1",
      "3:4",
      "4:3"
    ],
    "maxRefImages": 7,
    "refRoles": [
      {
        "name": "first_frame",
        "required": false,
        "min": 0,
        "max": 1
      },
      {
        "name": "last_frame",
        "required": false,
        "min": 0,
        "max": 1
      },
      {
        "name": "reference",
        "required": false,
        "min": 0,
        "max": 7
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 5000
    },
    "params": [
      {
        "name": "duration_seconds",
        "kind": "float",
        "default": 4,
        "min": 4,
        "max": 8
      },
      {
        "name": "resolution",
        "kind": "string",
        "enum": [
          "360p",
          "720p",
          "1080p"
        ]
      }
    ],
    "pricing": {
      "baseCostUsd": 0.2
    },
    "tags": [
      "text-to-video",
      "image-to-video",
      "reference-to-video"
    ],
    "referenceUrl": "https://platform.vidu.com/docs/quick-start"
  },
  {
    "id": "vidu/viduq1",
    "provider": "vidu",
    "displayName": "Vidu Q1",
    "description": "Vidu Q1 text/image/reference/start-end to video.",
    "mediaType": "video",
    "output": "video",
    "capabilities": {
      "textToImage": false,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": true,
      "imageToVideo": true
    },
    "sizes": [],
    "aspectRatios": [
      "16:9",
      "9:16",
      "1:1",
      "3:4",
      "4:3"
    ],
    "maxRefImages": 7,
    "refRoles": [
      {
        "name": "first_frame",
        "required": false,
        "min": 0,
        "max": 1
      },
      {
        "name": "last_frame",
        "required": false,
        "min": 0,
        "max": 1
      },
      {
        "name": "reference",
        "required": false,
        "min": 0,
        "max": 7
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 5000
    },
    "params": [
      {
        "name": "duration_seconds",
        "kind": "float",
        "default": 5,
        "min": 4,
        "max": 5
      },
      {
        "name": "resolution",
        "kind": "string",
        "enum": [
          "360p",
          "720p",
          "1080p"
        ]
      }
    ],
    "pricing": {
      "baseCostUsd": 0.3
    },
    "tags": [
      "text-to-video",
      "image-to-video",
      "reference-to-video"
    ],
    "referenceUrl": "https://platform.vidu.com/docs/quick-start"
  },
  {
    "id": "vidu/viduq2-pro",
    "provider": "vidu",
    "displayName": "Vidu Q2 Pro",
    "description": "Vidu Q2 Pro high-quality text/image/reference to video.",
    "mediaType": "video",
    "output": "video",
    "capabilities": {
      "textToImage": false,
      "imageToImage": false,
      "inpainting": false,
      "textToVideo": true,
      "imageToVideo": true
    },
    "sizes": [],
    "aspectRatios": [
      "16:9",
      "9:16",
      "1:1",
      "3:4",
      "4:3"
    ],
    "maxRefImages": 7,
    "refRoles": [
      {
        "name": "first_frame",
        "required": false,
        "min": 0,
        "max": 1
      },
      {
        "name": "last_frame",
        "required": false,
        "min": 0,
        "max": 1
      },
      {
        "name": "reference",
        "required": false,
        "min": 0,
        "max": 7
      }
    ],
    "promptLimits": {
      "required": true,
      "maxLength": 5000
    },
    "params": [
      {
        "name": "duration_seconds",
        "kind": "float",
        "default": 5,
        "min": 4,
        "max": 8
      },
      {
        "name": "resolution",
        "kind": "string",
        "enum": [
          "720p",
          "1080p"
        ]
      }
    ],
    "pricing": {
      "baseCostUsd": 0.4
    },
    "tags": [
      "text-to-video",
      "image-to-video",
      "reference-to-video",
      "premium"
    ],
    "referenceUrl": "https://platform.vidu.com/docs/quick-start"
  }
];
