/**
 * Shared data for the Storybook stories (`*.stories.tsx`). Imported by stories
 * only — nothing in the app graph reaches it, so it never ships in the
 * dashboard bundle. It lives under src/ (not .storybook/) so `tsc -b` type-
 * checks it against the real SDK types along with the stories.
 *
 * Every URL points at real bytes under /fixtures/ (generated by
 * .storybook/fixtures/make_fixtures.py, served via `staticDirs`), so the 3D
 * stories load and render actual meshes.
 */
import type { Generation, Model3dAsset } from '@litegen/sdk';

/** Absolute URL of a fixture, like the gateway's absolute asset URLs. Resolved
 *  against the preview iframe, so it works wherever Storybook is hosted. */
export function fixtureUrl(name: string): string {
  return new URL(`fixtures/${name}`, document.baseURI).href;
}

// Sizes and polycounts as printed by make_fixtures.py (its output is
// deterministic, so these stay true until the script changes).
export const CUBE_MESH: Model3dAsset = {
  kind: 'mesh', url: fixtureUrl('cube.glb'), format: 'glb', size_bytes: 3204, polycount: 12,
};
export const ICOSPHERE_MESH: Model3dAsset = {
  kind: 'mesh', url: fixtureUrl('icosphere.glb'), format: 'glb', size_bytes: 93180, polycount: 5120,
};
export const TEXTURE: Model3dAsset = {
  kind: 'texture', url: fixtureUrl('texture.png'), format: 'png', size_bytes: 1081, width: 256, height: 256,
};
export const PREVIEW: Model3dAsset = {
  kind: 'preview', url: fixtureUrl('preview.png'), format: 'png', size_bytes: 1170, width: 256, height: 256,
};
/** A GLB header followed by a truncated JSON chunk: parses as glTF, then fails. */
export const CORRUPT_MESH: Model3dAsset = {
  kind: 'mesh', url: fixtureUrl('corrupt.glb'), format: 'glb', size_bytes: 100,
};
/** Deliberately absent from the fixtures directory, so the request 404s. */
export const MISSING_MESH: Model3dAsset = {
  kind: 'mesh', url: fixtureUrl('does-not-exist/model.glb'), format: 'glb',
};

/** What a textured provider returns: mesh + base-colour map + 2D preview. */
export const FULL_ASSETS: Model3dAsset[] = [CUBE_MESH, TEXTURE, PREVIEW];

/** An image generation's output. */
export const IMAGE_URL = fixtureUrl('image.png');
/** A video URL that 404s. */
export const MISSING_VIDEO_URL = fixtureUrl('does-not-exist/clip.mp4');

/** A generation row with every required field set; override what the story is about. */
export function generation(overrides: Partial<Generation> = {}): Generation {
  return {
    id: 'gen_story_3d_0001',
    key_id: null,
    model: 'mock/mesh-3d',
    provider: 'mock',
    media_type: 'model3d',
    status: 'completed',
    progress: 100,
    cost_usd: 0.04,
    created_at: '2026-09-11T08:00:00Z',
    completed_at: '2026-09-11T08:01:12Z',
    provider_job_id: 'mock-job-0001',
    result_url: CUBE_MESH.url,
    metadata: { assets: FULL_ASSETS },
    error_message: null,
    ...overrides,
  };
}

let clip: Promise<string | null> | undefined;

/**
 * A short, genuinely playable WebM clip for the video stories, recorded from
 * an animated canvas with MediaRecorder and returned as a blob: URL (null when
 * the browser cannot record). Generated in the browser because a stdlib-only
 * script cannot encode a video codec; recorded once per page and reused.
 */
export function demoClip(): Promise<string | null> {
  clip ??= record();
  return clip;
}

async function record(): Promise<string | null> {
  if (typeof MediaRecorder === 'undefined') return null;
  const mimeType = ['video/webm;codecs=vp9', 'video/webm;codecs=vp8', 'video/webm']
    .find(m => MediaRecorder.isTypeSupported(m));
  const canvas = document.createElement('canvas');
  canvas.width = 320;
  canvas.height = 180;
  const ctx = canvas.getContext('2d');
  if (!mimeType || !ctx) return null;

  const recorder = new MediaRecorder(canvas.captureStream(30), { mimeType });
  const chunks: Blob[] = [];
  recorder.ondataavailable = e => { if (e.data.size > 0) chunks.push(e.data); };
  const stopped = new Promise<void>(resolve => { recorder.onstop = () => resolve(); });

  const draw = (frame: number) => {
    const t = frame / 30;
    const sky = ctx.createLinearGradient(0, 0, 0, 180);
    sky.addColorStop(0, '#1b1f4b');
    sky.addColorStop(1, '#f78166');
    ctx.fillStyle = sky;
    ctx.fillRect(0, 0, 320, 180);
    ctx.fillStyle = '#ffd33d';
    ctx.beginPath();
    ctx.arc(160, 150 - t * 40, 34, 0, Math.PI * 2);
    ctx.fill();
    ctx.fillStyle = '#0d1117';
    ctx.fillRect(0, 130, 320, 50);
  };

  recorder.start();
  await new Promise<void>(resolve => {
    let frame = 0;
    const timer = window.setInterval(() => {
      draw(frame++);
      if (frame > 45) { window.clearInterval(timer); resolve(); }
    }, 1000 / 30);
  });
  recorder.stop();
  await stopped;
  return chunks.length ? URL.createObjectURL(new Blob(chunks, { type: 'video/webm' })) : null;
}

/** Path marker the stalled-download interceptor answers for. */
const STALLED_MARKER = '/__stalled__/';
/** A mesh URL whose download delivers 40% of the icosphere and then hangs,
 *  pinning the viewer in its "streaming the mesh" state. */
export const STALLED_MESH_URL = fixtureUrl(`${STALLED_MARKER.slice(1)}icosphere.glb`);

let stallInstalled = false;

/**
 * Pins the viewer's loading state, which in the live app lasts only as long
 * as a download does. Wraps `fetch` (three.js's FileLoader, inside
 * model-viewer, loads meshes with it) for URLs under STALLED_MARKER only:
 * the real icosphere is fetched, 40% of it is streamed with its true
 * Content-Length so the progress bar has a real fraction, and the stream is
 * then left open. Every other request passes through untouched, so it is safe
 * to leave installed for the rest of the Storybook session.
 */
export function installStalledMeshRoute(): void {
  if (stallInstalled) return;
  stallInstalled = true;
  const realFetch = window.fetch.bind(window);
  window.fetch = async (input, init) => {
    const url = input instanceof Request ? input.url : String(input);
    if (!url.includes(STALLED_MARKER)) return realFetch(input, init);
    const bytes = new Uint8Array(await (await realFetch(url.replace(STALLED_MARKER, '/'))).arrayBuffer());
    const partial = bytes.subarray(0, Math.floor(bytes.length * 0.4));
    const body = new ReadableStream<Uint8Array>({
      start(controller) { controller.enqueue(partial); /* never closed */ },
    });
    return new Response(body, {
      status: 200,
      headers: { 'Content-Type': 'model/gltf-binary', 'Content-Length': String(bytes.length) },
    });
  };
}
