/**
 * Pure helpers for the model-capability reference: turn a parsed `models/*.yaml`
 * model object into the slim `ModelEntry` shape the landing page renders, and
 * render the generated TS module. Kept dependency-free + side-effect-free so it
 * can be unit-tested (see derive-models.test.mjs).
 *
 * Derivation mirrors the Rust projection in litegen-core
 * (`project_model_info` / `extract_sizes`): sizes come from the `size` param
 * (enum mode), aspect ratios from `aspect_ratio.allowed`, max ref images from
 * `ref_inputs.max_total`. Everything else is read straight from the YAML.
 */

/**
 * Most-applicable developer/API documentation URL per provider. Used as each
 * model's reference link (the registry YAML carries no URLs). Verified to
 * resolve to docs (not marketing/pricing); a few are the best-available
 * official portal where the vendor has no clean dedicated API-docs page.
 */
export const PROVIDER_DOCS = {
  openai: 'https://platform.openai.com/docs/guides/image-generation',
  google: 'https://ai.google.dev/gemini-api/docs',
  stability: 'https://platform.stability.ai/docs/api-reference',
  bfl: 'https://docs.bfl.ml/',
  ideogram: 'https://developer.ideogram.ai/',
  recraft: 'https://www.recraft.ai/docs/api-reference/getting-started',
  leonardo: 'https://docs.leonardo.ai/',
  runway: 'https://docs.dev.runwayml.com/',
  luma: 'https://docs.lumalabs.ai/docs/api',
  kling: 'https://app.klingai.com/global/dev/document-api/quickStart/productIntroduction/overview',
  minimax: 'https://platform.minimax.io/docs',
  bytedance: 'https://docs.byteplus.com/en/docs/ModelArk/',
  bedrock: 'https://docs.aws.amazon.com/nova/latest/userguide/getting-started-api.html',
  hunyuan: 'https://www.tencentcloud.com/document/product/1284/74915',
  vidu: 'https://platform.vidu.com/docs/quick-start',
  pixverse: 'https://docs.platform.pixverse.ai/',
  replicate: 'https://replicate.com/docs/reference/http',
  fal: 'https://fal.ai/docs/documentation',
};

/** Map one parsed YAML model to a ModelEntry. Defensive about missing fields. */
export function deriveModel(m) {
  const params = m.params ?? {};

  const sizeParam = params.size;
  const sizes =
    sizeParam && sizeParam.mode === 'enum' && Array.isArray(sizeParam.values)
      ? sizeParam.values.map(([w, h]) => `${w}x${h}`)
      : [];

  const arParam = params.aspect_ratio;
  const aspectRatios =
    arParam && Array.isArray(arParam.allowed) ? arParam.allowed.slice() : [];

  const ri = m.ref_inputs;
  const refRoles = ri && ri.roles
    ? Object.entries(ri.roles).map(([name, r]) => ({
        name,
        required: r?.required === true,
        min: r?.min_count ?? 0,
        max: r?.max_count ?? 0,
      }))
    : [];

  // Display params: everything except size/aspect_ratio (shown separately).
  const displayParams = Object.entries(params)
    .filter(([name]) => name !== 'size' && name !== 'aspect_ratio')
    .map(([name, p]) => ({
      name,
      kind: p?.kind ?? 'string',
      enum: Array.isArray(p?.enum_values) ? p.enum_values.map(String) : undefined,
      default: p?.default !== undefined ? p.default : undefined,
      min: p?.min !== undefined ? p.min : undefined,
      max: p?.max !== undefined ? p.max : undefined,
    }));

  const caps = m.capabilities ?? {};
  const prompt = m.prompt ?? {};

  return {
    id: m.id,
    provider: m.provider,
    displayName: m.display_name ?? m.id,
    description: m.description ?? '',
    mediaType: m.media_type,
    output: m.media_type,
    capabilities: {
      textToImage: caps.text_to_image === true,
      imageToImage: caps.image_to_image === true,
      inpainting: caps.inpainting === true,
      textToVideo: caps.text_to_video === true,
      imageToVideo: caps.image_to_video === true,
    },
    sizes,
    aspectRatios,
    maxRefImages: ri?.max_total ?? 0,
    refRoles,
    promptLimits: {
      required: prompt.required !== false,
      minLength: prompt.min_length,
      maxLength: prompt.max_length,
    },
    params: displayParams,
    pricing:
      m.pricing?.base_cost_usd !== undefined
        ? { baseCostUsd: m.pricing.base_cost_usd }
        : undefined,
    tags: Array.isArray(m.tags) ? m.tags.slice() : [],
    referenceUrl: PROVIDER_DOCS[m.provider],
  };
}

/** Derive + sort a list of YAML models for stable generated output. */
export function deriveModels(yamlModels) {
  return yamlModels.map(deriveModel).sort((a, b) => a.id.localeCompare(b.id));
}

const HEADER = `// GENERATED by scripts/sync-models.mjs — do not edit by hand.
// Run \`npm run sync-models\` to refresh from the repo's models/*.yaml.`;

const INTERFACE = `export interface ModelParam {
  name: string;
  kind: string;
  enum?: string[];
  default?: string | number | boolean;
  min?: number;
  max?: number;
}

export interface ModelRefRole {
  name: string;
  required: boolean;
  min: number;
  max: number;
}

export interface ModelEntry {
  id: string;
  provider: string;
  displayName: string;
  description: string;
  mediaType: 'image' | 'video';
  output: 'image' | 'video';
  capabilities: {
    textToImage: boolean;
    imageToImage: boolean;
    inpainting: boolean;
    textToVideo: boolean;
    imageToVideo: boolean;
  };
  sizes: string[];
  aspectRatios: string[];
  maxRefImages: number;
  refRoles: ModelRefRole[];
  promptLimits: { required: boolean; minLength?: number; maxLength?: number };
  params: ModelParam[];
  pricing?: { baseCostUsd: number };
  tags: string[];
  /** Most-applicable provider documentation URL. */
  referenceUrl?: string;
}`;

/** Render the generated TS module. The data is plain JSON, valid as a TS literal. */
export function renderGeneratedTs(models) {
  return `${HEADER}
${INTERFACE}

export const MODELS: ModelEntry[] = ${JSON.stringify(models, null, 2)};
`;
}

/**
 * Compact per-provider model index (display names grouped by output modality) —
 * a small module the diagram imports for its node detail panels, so the homepage
 * doesn't pull the full MODELS catalog.
 */
export function buildProviderModels(models) {
  const out = {};
  for (const m of models) {
    const p = (out[m.provider] ??= { image: [], video: [] });
    const name = m.displayName || m.id;
    if (m.output === 'video') p.video.push(name);
    else p.image.push(name);
  }
  return out;
}

export function renderProviderModelsTs(models) {
  const map = buildProviderModels(models);
  const lines = Object.keys(map)
    .sort()
    .map((id) => `  ${JSON.stringify(id)}: ${JSON.stringify(map[id])},`);
  return `// GENERATED by scripts/sync-models.mjs — do not edit by hand.
// Per-provider model lists for the InfraFlow node detail panels.
export interface ProviderModels {
  image: string[];
  video: string[];
}

export const PROVIDER_MODELS: Record<string, ProviderModels> = {
${lines.join('\n')}
};
`;
}
