//! OpenAPI aggregator. Drives `/openapi.json` which the first-party SDKs consume.
use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    info(
        title = "LiteGen API",
        version = env!("CARGO_PKG_VERSION"),
        description = "Universal proxy for AI image and video generation."
    ),
    paths(
        crate::api::handlers::generate_image,
        crate::api::handlers::estimate_image_cost,
        crate::api::handlers::generate_video,
        crate::api::handlers::estimate_video_cost,
        crate::api::handlers::get_video_status,
        crate::api::handlers::list_models,
        crate::api::handlers::get_model_schema,
        crate::api::handlers::health_check,
        crate::api::handlers::liveness,
        crate::api::handlers::get_stats,
        crate::api::handlers::get_logs,
        crate::api::handlers::create_api_key,
        crate::api::handlers::list_api_keys,
        crate::api::handlers::revoke_api_key,
        crate::api::handlers::clear_cache,
        // Auth — password
        crate::api::handlers::auth_password::signup,
        crate::api::handlers::auth_password::login,
        crate::api::handlers::auth_password::logout,
        crate::api::handlers::auth_password::me,
        crate::api::handlers::auth_password::csrf_token,
        crate::api::handlers::auth_password::password_reset_request,
        crate::api::handlers::auth_password::password_reset_confirm,
        // Auth — OAuth
        crate::api::handlers::oauth::github_start,
        crate::api::handlers::oauth::github_callback,
        crate::api::handlers::oauth::google_start,
        crate::api::handlers::oauth::google_callback,
        // Users + invitations
        crate::api::handlers::users::list_users,
        crate::api::handlers::users::invite_user,
        crate::api::handlers::users::get_invitation,
        crate::api::handlers::users::accept_invitation,
        crate::api::handlers::users::patch_user,
        crate::api::handlers::users::delete_user,
        crate::api::handlers::users::transfer_owner,
        // Account
        crate::api::handlers::account::get_account,
        crate::api::handlers::account::patch_account,
        crate::api::handlers::account::list_sessions,
        crate::api::handlers::account::revoke_session,
    ),
    components(schemas(
        // Request / response types (from `types`)
        crate::types::BaseGenerationRequest,
        crate::types::ImageGenerationRequest,
        crate::types::ImageGenerationResponse,
        crate::types::ImageResult,
        crate::types::VideoGenerationRequest,
        crate::types::VideoGenerationResponse,
        crate::types::ReferenceImage,
        crate::types::RefImageKind,
        crate::types::GenerationStatus,
        crate::types::MediaType,
        crate::types::CostSource,
        crate::types::UsageInfo,
        crate::types::CostEstimate,
        crate::types::ModelInfo,
        crate::types::ModelCapabilities,
        crate::types::ModelPricing,
        crate::types::ProviderConfig,
        crate::types::ApiKeyEntry,
        crate::types::ModelRoute,
        crate::types::Deployment,
        crate::types::RoutingStrategy,
        crate::types::CacheConfig,
        crate::types::ProviderHealth,
        crate::types::RequestLog,
        crate::types::ProxyStats,
        crate::types::ModelUsageStat,
        crate::types::ProviderUsageStat,
        crate::types::ErrorResponse,
        crate::types::ErrorDetail,
        crate::types::ApiKey,
        crate::types::LivenessResponse,
        crate::types::CacheStatus,
        crate::types::HealthResponse,
        crate::types::ModelListResponse,
        crate::types::ApiKeyInfo,
        crate::types::ApiKeyListResponse,
        crate::types::ApiKeyCreatedResponse,
        crate::types::RevokeKeyResponse,
        crate::types::CacheClearedResponse,
        // User / session / invitation domain types
        crate::types::User,
        crate::types::Role,
        crate::types::Session,
        crate::types::Invitation,
        crate::types::PasswordReset,
        // Auth handler schemas
        crate::api::handlers::auth_password::PublicUser,
        crate::api::handlers::auth_password::AuthResponse,
        crate::api::handlers::auth_password::SignupRequest,
        crate::api::handlers::auth_password::LoginRequest,
        crate::api::handlers::auth_password::CsrfResponse,
        crate::api::handlers::auth_password::PasswordResetRequestBody,
        crate::api::handlers::auth_password::PasswordResetConfirmBody,
        // Users handler schemas
        crate::api::handlers::users::PublicUser,
        crate::api::handlers::users::InviteRequest,
        crate::api::handlers::users::InviteResponse,
        crate::api::handlers::users::InvitationView,
        crate::api::handlers::users::AcceptInvitationRequest,
        crate::api::handlers::users::PatchUserRequest,
        crate::api::handlers::users::TransferOwnerRequest,
        // Account handler schemas
        crate::api::handlers::account::AccountUser,
        crate::api::handlers::account::SessionInfo,
        crate::api::handlers::account::PatchAccountRequest,
        // Capability schema (response of GET /v1/models/{id}).
        // `MediaType` and `ModelPricing` are renamed via `#[schema(as = ...)]` to
        // avoid collisions with the same-named types in `crate::types`.
        crate::capabilities::ModelSchema,
        crate::capabilities::ModelCapabilityFlags,
        crate::capabilities::ModelPricing,
        crate::capabilities::PromptSpec,
        crate::capabilities::ParamSpec,
        crate::capabilities::ParamSpecBool,
        crate::capabilities::ParamSpecInt,
        crate::capabilities::ParamSpecFloat,
        crate::capabilities::ParamSpecString,
        crate::capabilities::ParamSpecAspectRatio,
        crate::capabilities::ParamSpecSeed,
        crate::capabilities::SizeSpec,
        crate::capabilities::SizeSpecFreeform,
        crate::capabilities::SizeSpecEnum,
        crate::capabilities::RefInputSpec,
        crate::capabilities::RefRoleSpec,
        crate::capabilities::RefProviderFormat,
        crate::capabilities::RefProviderFormatMultipart,
        crate::capabilities::MediaType,
    )),
    tags(
        (name = "Images", description = "Image generation endpoints"),
        (name = "Videos", description = "Video generation endpoints"),
        (name = "Models", description = "Model discovery"),
        (name = "System", description = "Health checks"),
        (name = "Dashboard", description = "Stats and logs"),
        (name = "Admin", description = "API key management"),
        (name = "Auth", description = "Authentication (password + OAuth)"),
        (name = "Users", description = "User management and invitations"),
        (name = "Account", description = "Current user account and sessions"),
    )
)]
pub struct ApiDoc;
